### ISSUE TITLE
How does this package handle soft link?

### ISSUE THREAD

**Issue by prcups** [dmerejkowsky/rusync#16]
Is rusync have the ability to sync soft link? In Linux Shell, the rsync command will copy soft link as configured by env.

**Comment by dmerejkowsky** [comment]
I think so. We try to be smart about symlinks without exposing too many configuration options.

You can take a look at the [test suite](https://github.com/dmerejkowsky/rusync/blob/master/src/fsops.rs#L280-L337) to see how rusync handles symlinks - please tell me if something is not clear or does not match your expected behavior.

**Comment by dmerejkowsky** [comment]
I'm going to assume this answered your question. Feel free to re-open if it's not the case :stuck_out_tongue:
